apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: item-deployment
spec:
  selector:
    matchLabels:
      app: item-service
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
      - name: item-service
        image: ram3shpala/item-docker:latest
        ports:
        - containerPort: 80